### PR TITLE
Fixes and updates 2023-02

### PR DESCRIPTION
**Pull request by patrickcping**
- Changes to make this sample app more eu, ca and asia friendly. (26)

- Fixes broken build script (25)

### CODE REVIEW

**Comment by icsrmontano** [comment]
It would be nice to get this code merged in the near future. I'm using a canadian tenant and got stuck for a few hours until I found this PR @patrickcping

**Comment by patrickcping** [comment]
@richardcardona

**Comment by richardcardona** [comment]
The Security team only merges high or critical Dependabot vulnerability fix PRs. Please tag the project author or an engineering team member for functional fixes.

**Comment by patrickcping** [comment]
Unfortunately our existing maintainers had moved on.  I've now been given maintainer rights to be able to review and merge functional fixes such as these - I'll look to review and resolve this PR shortly

**Pull request merged**
